name: Module pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
            go-version-file: './go.mod'
            cache-dependency-path: './go.sum'
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v2.0.2

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: ensure compilation
        run: go build

      - name: install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: go test
        timeout-minutes: 30
        run: make test
